version: "3"

services:
  loconotion:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: loconotion:latest
    volumes:
      - ${LOCONOTION_LOCAL_DIST:-/tmp/}:/app/loconotion/dist
    restart: always